<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Kab BekasiKab PurwakartaKab Karawang_483fbb_1</name>
   <tag></tag>
   <elementGuidId>d4140b50-187e-4e5e-beb1-88c6640b0f9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;cityOfResidence&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='cityOfResidence']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cityOfResidence</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kota Depok</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>cityOfResidence</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cityOfResidence</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-personaldata form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kab. BekasiKab. PurwakartaKab. KarawangKab. BogorKab. SukabumiKab. CianjurKab. BandungKab. SumedangKab. TasikmalayaKab. GarutKab. CiamisKab. CirebonKab. KuninganKab. IndramayuKab. MajalengkaKab. SubangKab. Bandung BaratKota BanjarKota BandungKota BogorKota SukabumiKota CirebonKota TasikmalayaKota CimahiKota DepokKota BekasiKab. LebakKab. PandeglangKab. SerangKab. TangerangKota CilegonKota TangerangKota SerangKota Tangerang SelatanWil. Kota Jakarta PusatWil. Kota Jakarta UtaraWil. Kota Jakarta BaratWil. Kota Jakarta SelatanWil. Kota Jakarta TimurKab. Kepulauan SeribuKab. BantulKab. SlemanKab. Gunung KidulKab. Kulon ProgoKab./Kota Lainnya di YogyaKota YogyakartaKab. SemarangKab. KendalKab. DemakKab. GroboganKab. PekalonganKab. TegalKab. BrebesKab. PatiKab. KudusKab. PemalangKab. JeparaKab. RembangKab. BloraKab. BanyumasKab. CilacapKab. PurbalinggaKab. BanjarnegaraKab. MagelangKab. TemanggungKab. WonosoboKab. PurworejoKab. KebumenKab. KlatenKab. BoyolaliKab. SragenKab. SukoharjoKab. KaranganyarKab. WonogiriKab. BatangKab./Kota Lainnya di Jawa TengahKota SemarangKota SalatigaKota PekalonganKota TegalKota MagelangKota Surakarta/SoloKab. GresikKab. SidoarjoKab. MojokertoKab. JombangKab. SampangKab. PamekasanKab. SumenepKab. BangkalanKab. BondowosoKab. BanyuwangiKab. JemberKab. MalangKab. PasuruanKab. ProbolinggoKab. LumajangKab. KediriKab. NganjukKab. TulungagungKab. TrenggalekKab. BlitarKab. MadiunKab. NgawiKab. MagetanKab. PonorogoKab. PacitanKab. BojonegoroKab. TubanKab. LamonganKab. SitubondoKota BatuKab./Kota Lainnya di Jawa TimurKota SurabayaKota MojokertoKota MalangKota PasuruanKota ProbolinggoKota BlitarKota KediriKota MadiunKab. Bengkulu SelatanKab. Bengkulu UtaraKab. Rejang LebongKab. LebongKab. KepahiangKab. MukomukoKab. SelumaKab. KaurKab. Bengkulu TengahKab./Kota Lainnya di BengkuluKota BengkuluKab. BatanghariKab. SarolangunKab. KerinciKab. Muaro JambiKab. Tanjung Jabung BaratKab. Tanjung Jabung TimurKab. TeboKab. MeranginKab. BungoKab./Kota Lainnya di JambiKota JambiKota Sungai PenuhKab. Aceh BesarKab. PidieKab. Aceh UtaraKab. Aceh TimurKab. Aceh SelatanKab. Aceh BaratKab. Aceh TengahKab. Aceh TenggaraKab. Aceh SingkilKab. Aceh Jeumpa/BireuenKab. Aceh TamiangKab. Gayo LuesKab. Aceh Barat DayaKab. Aceh JayaKab. Nagan RayaKab. SimeuleuKab. Bener MeriahKab. Pidie JayaKab. SubulussalamKab./Kota Lainnya di AcehKota Banda AcehKota SabangKota LhokseumaweKota LangsaKab. Deli SerdangKab. LangkatKab. KaroKab. SimalungunKab. Labuhan BatuKab. AsahanKab. DairiKab. Tapanuli UtaraKab. Tapanuli TengahKab. Tapanuli SelatanKab. NiasKab. Toba SamosirKab. Mandailing NatalKab. Nias SelatanKab. Humbang HasundutanKab. Pakpak BharatKab. SamosirKab. Serdang BedagaiKab. Batu BaraKab. Padang LawasKab. Padang Lawas UtaraKab. Labuanbatu SelatanKab. Labuanbatu UtaraKab. Nias BaratKab. Nias UtaraKota Gunung SitoliKab/Kota Lainnya di Sumatera UtaraKota Tebing TinggiKota BinjaiKota Pematang SiantarKota Tanjung BalaiKota SibolgaKota MedanKota Padang SidempuanKab. AgamKab. PasamanKab. Lima Puluh KotaKab. Solok SelatanKab. Padang PariamanKab. Pesisir SelatanKab. Tanah DatarKab. SijunjungKab. Kepulauan MentawaiKab. Pasaman BaratKab. DharmasrayaKab. SolokKab/Kota Lainnya di Sumatera BaratKota BukittinggiKota PadangKota SawahluntoKota Padang PanjangKota SolokKota PayakumbuhKota PariamanKab. KamparKab. BengkalisKab. Indragiri HuluKab. Indragiri HilirKab. Rokan HuluKab. Rokan HilirKab. PelalawanKab. SiakKab. Kuantan SingingiKab. Kepulauan MerantiKab./Kota Lainnya di RiauKota PekanbaruKota DumaiKab. Musi BanyuasinKab. Ogan Komering UluKab. Lematang Ilir Ogan Tengah (Muara Enim)Kab. LahatKab. Musi RawasKab. Ogan Komering IlirKab. BanyuasinKab. Ogan Komering Ulu SelatanKab. Ogan Komering Ulu TimurKab. Ogan IlirKab. Empat LawangKab./Kota Lainnya di Sumatera SelatanKota PalembangKota LubuklinggauKota PrabumulihKota Pagar AlamKab. BangkaKab. BelitungKab. Bangka BaratKab. Bangka SelatanKab. Bangka TengahKab. Belitung TimurKab. Bangka BelitungKab./Kota Lainnya di Bangka BelitungKota Pangkal PinangKab. KarimunKab. LinggaKab. NatunaKab. Bintan (d/h Kabupaten Kepulauan Riau)Kab. Kep. AnambasKab./Kota Lainnya di Kepulauan RiauKota Tanjung PinangKota BatamKab. Lampung SelatanKab. Lampung TengahKab. Lampung UtaraKab. Lampung BaratKab. Tulang BawangKab. TanggamusKab. Lampung TimurKab. Way KananKab. PesawaranKab. PringsewuKab. Tulang Bawang BaratKab. MesujiKab. Pesisir BaratKab./Kota Lainnya di LampungKota Bandar LampungKota MetroKab. BanjarKab. Tanah LautKab. TapinKab. Hulu Sungai SelatanKab. Hulu Sungai TengahKab. Hulu Sungai UtaraKab. Barito KualaKab. Kota BaruKab. TabalongKab.Tanah BumbuKab. BalanganKab./Kota Lainnya di Kalimantan SelatanKota BanjarmasinKota BanjarbaruKab. PontianakKab. SambasKab. KetapangKab. SanggauKab. SintangKab. Kapuas HuluKab. BengkayangKab. LandakKab. SekadauKab. MelawiKab. Kayong UtaraKab. Kubu RayaKab./Kota Lainnya di Kalimantan BaratKota PontianakKota SingkawangKab. Kutai KartanegaraKab. BerauKab. PaserKab. BulunganKab. Kutai BaratKab. Kutai TimurKab. NunukanKab. MalinauKab. Penajam Paser UtaraKab. Tana TidungKab. Mahakam UluKab./Kota Lainnya di Kalimantan TimurKota SamarindaKota BalikpapanKota TarakanKota BontangKab./Kota Lainnya di Kalimantan UtaraKab. KapuasKab. Kotawaringin BaratKab. Kotawaringin TimurKab. Murung RayaKab. Barito TimurKab. Barito SelatanKab. Gunung MasKab. Barito UtaraKab. Pulang PisauKab. SeruyanKab. KatinganKab. SukamaraKab. LamandauKab./Kota Lainnya di Kalimantan TengahKota PalangkarayaKab. DonggalaKab. PosoKab. BanggaiKab. Toli-ToliKab.Banggai KepulauanKab. MorowaliKab. BuolKab. Tojo Una-UnaKab. Parigi MoutongKab. SigiKab. Banggai LautKab. Morowali UtaraKab./Kota Lainnya di Sulawesi TengahKota PaluKab. PinrangKab. GowaKab. WajoKab. BoneKab. Tana TorajaKab. MarosKab. LuwuKab. SinjaiKab. BulukumbaKab. BantaengKab. JenepontoKab. Kep. SelayarKab. TakalarKab. BarruKab. Sidereng RappangKab. Pangkajene KepulauanKab. Soppeng (d/h Watansoppeng)Kab. EnrekangKab. Luwu Timur (d/h Luwu Selatan)Kab. Luwu UtaraKab. Toraja UtaraKab./Kota Lainnya di Sulawesi SelatanKota MakassarKota Pare-PareKota PalopoKab. MinahasaKab. Bolaang MongondowKab. Kepulauan SangiheKab. Kepulauan TalaudKab. Minahasa SelatanKab. Minahasa UtaraKab. Minahasa TenggaraKab. Bolaang Mongondow UtaraKab. SitaroKab. Bolaang Mongondow SelatanKab. Bolaang Mongondow TimurKab./Kota Lainnya di Sulawesi UtaraKota ManadoKota KotamobaguKota BitungKota. TomohonKab. GorontaloKab. BoalemoKab. Bone BolangoKab. PohuwatoKab. Gorontalo UtaraKab./Kota Lainnya di GorontaloKota GorontaloKab. Polewali MandarKab. MajeneKab. MamasaKab. Mamuju UtaraKab. Mamuju TengahKab./Kota Lainnya di Sulawesi BaratKota MamujuKab. ButonKab. MunaKab. KolakaKab. WakatobiKab. KonaweKab. Konawe SelatanKab. BombanaKab. Kolaka UtaraKab. Buton UtaraKab. Konawe UtaraKab. Kolaka TimurKonawe KepulauanKab./Kota Lainnya di Sulawesi TenggaraKota Bau-BauKota KendariKab. Lombok BaratKab. Lombok TengahKab. Lombok TimurKab. SumbawaKab. BimaKab. DompuKab. Sumbawa BaratKab. Lombok UtaraKab./Kota Lainnya di Nusa Tenggara BaratKota MataramKota. BimaKab. BulelengKab. JembranaKab. TabananKab. BadungKab. GianyarKab. KlungkungKab. BangliKab. KarangasemKab./Kota Lainnya di BaliKota DenpasarKab. KupangKab. Timor-Tengah SelatanKab. Timor-Tengah UtaraKab. BeluKab. AlorKab. Flores TimurKab. SikkaKab. EndeKab. NgadaKab. ManggaraiKab. Sumba TimurKab. Sumba BaratKab. LembataKab. RoteKab. Manggarai BaratKab. Sumba TengahKab. Sumba Barat DayaKab. Manggarai TimurKab. NagekeoKab. RaijuaKab. MalakaKab./Kota Lainnya di Nusa Tenggara TimurKota KupangKab. Maluku TengahKab. Maluku TenggaraKab. Maluku Tenggara BaratKab. BuruKab. Seram Bagian BaratKab. Seram Bagian TimurKab. Kepulauan AruKab. Maluku Barat DayaKab. Buru SelatanKab./Kota Lainnya di MalukuKota AmbonKota TualKab. JayapuraKab. Biak NumforKab. Yapen-WaropenKab. MeraukeKab. PaniaiKab. JayawijayaKab. NabireKab. MimikaKab. Puncak JayaKab. SarmiKab. KeeromKab. Pegunungan BintangKab. YahukimoKab. TolikaraKab. WaropenKab. Boven DigoelKab. MappiKab. AsmatKab. SupioriKab. Mamberamo RayaKab. DogiyaiKab. Lanny JayaKab. Mamberamo TengahKab. Nduga TengahKab. YalimoKab. PuncakKab. Intan JayaKab. DeiyaiKab./Kota Lainnya di PapuaKota JayapuraKab. Halmahera TengahKab. Halmahera UtaraKab. Halmahera TimurKab. Halmahera BaratKab. Halmahera SelatanKab. Kepulauan SulaKab. Pulau MorotaiKab. Pulau TaliabuKab./Kota Lainnya di Maluku UtaraKota TernateKota Tidore KepulauanKab. SorongKab. Fak-FakKab. ManokwariKab. Sorong SelatanKab. Raja AmpatKab. KaimanaKab. Teluk BintuniKab. Teluk WondamaKab. TembrauwKab. MaybratKab. Pegunungan ArfakKab. Manokwari SelatanKab./Kota Lainnya di Papua BaratKota SorongAfganistanKepulauan AlandAlbaniaAljazairSamoa AmerikaAndorraAngolaAnguillaAntartikaAntigua dan BarbudaArgentinaArmeniaArubaAustraliaAustriaAzerbaijanBahamaBahrainBangladeshBarbadosBelarusBelgiaBelizeBeninBermudaBhutanBoliviaBosnia dan HerzegovinaBotswanaPulau BouvetBrazilBritania di Samudra HindiaBrunei DarussalamBulgariaBurkina FasoBurundiKambojaKamerunKanadaCape VerdeKepulauan CaymanRepublik Afrika TengahChadChiliCinaPulau NatalPulau Cocos (Keeling)KolumbiaKomoroKongoRepublik Demokratik KongoKepulauan CookKosta RikaCote D'IvoireKroasiaKubaSiprusRepublik CekoDenmarkDjiboutiDominicaRepublik DominikaEkuadorMesirEl SalvadorGuinea ekuatorEritreaEstoniaEtiopiaKepulauan Falkland (Malvinas)Kepulauan FaroeFijiFinlandiaPerancisGuyana PerancisPolinesia PerancisTeritorial Prancis SelatanGabonGambiaGeorgiaJermanGhanaGibraltarYunaniGreenlandGrenadaGuadeloupeGuamGuatemalaGuernseyGuineaGuinea-BissauguyanaHaitiPulau Heard &amp; Pulau McdonaldHoly See (Vatican City State)HondurasHongkongHungariaIslandiaIndiaRepublik Islam IranIrakIrlandiaIsle of ManIsraelItaliaJamaikaJepangJerseyYordaniaKazakhstanKenyaKiribatiKoreaKuwaitKyrgyzstanRepublik Demokratik Lao People'sLatviaLibanonLesothoLiberiaLibyan Arab JamahiriyaLiechtensteinLithuaniaLuksemburgMacaoMakedoniaMadagaskarMalawiMalaysiaMaladewaMaliMaltaPulau MarshallMartiniqueMauritaniaMauritiusMayotteMeksikoFederasi Serikat Dari MikronesiaMoldovaMonakoMongoliaMontenegroMontserratMarokoMozambikMyanmarNamibiaNauruNepalBelandaAntillen BelandaKaledonia BaruSelandia BaruNikaraguaNigerNigeriaNiuePulau NorfolkKepulauan Mariana UtaraNorwayOmanPakistanPalauPalestinaPanamaPapua NuginiParaguayPeruFilipinaPitcairnPolandiaPortugalPuerto RicoQatarReuniRumaniaRusiaRwandaSaint BarthelemySaint HelenaSaint Kitts dan NevisSaint LuciaSaint MartinSaint Pierre Dan MiquelonSaint Vincent dan GrenadinesSamoaSan MarinoSao Tome Dan PrincipeArab SaudiSenegalSerbiaSeychellesSierra LeoneSingapuraSlowakiaSloveniaPulau SolomonSomaliaAfrika SelatanGeorgia Selatan dan Pulau SandwichSpanyolSrilankaSudanSurinameSvalbard Dan Jan MayenSwazilandSwediaSwissSyriaTaiwanTajikistanTanzaniaThailandTimor-LesteTogoTokelauTongaTrinidad dan TobagoTunisiaTurkiTurkmenistanKepulauan Turks dan CaicosTuvaluUgandaUkrainaUni Emirat ArabUnited KingdomAmerika SerikatUruguayUzbekistanVanuatuVenezuelaVietnamKepulauan Virgin, InggrisKepulauan Virgin, ASWallis dan FutunaSahara BaratYamanZambiaZimbabwe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;fade modal-verification  modal show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;personal-data p-0 container&quot;]/form[1]/div[@class=&quot;form-group&quot;]/div[@class=&quot;input-group&quot;]/select[@class=&quot;input-personaldata form-control&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='cityOfResidence']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jika tempat tinggal kamu saat ini di luar Indonesia, silakan pilih negara tempat tinggal kamu.'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALAMAT TERKINI'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIMPAN'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
   </webElementXpaths>
</WebElementEntity>
